# api_key: your_api_key_here
llm:
  ## OpenAI
  # model: "openai/gpt-4"

  ## Gemini
  # model: "gemini-2.5-flash"   # or "gemini-2.5-pro"; API key must be set in environment variable GOOGLE_API_KEY (current quota exceeded)

  ## Ollama
  # provider: ollama
  # model: "deepseek-r1:14b"   # any local model tag shown by `ollama list`
  
  ## openrouter
  provider: openrouter
  # model: "deepseek/deepseek-r1-0528:free"
  model: "moonshotai/kimi-k2:free"
  api_key: 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
  temperature: 0.7
  provider: openai
  chunk_size: 1000
output:
  path: data/output.json
extraction:
  schema: 
    - title
    - authors
    - abstract
    - keywords
    - publication_date
    - url