name: CI
on:
  push:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          python3 -m pip install pip --upgrade
          python3 -m pip install ruff
      - run: ./tests/lint.sh
